### ISSUE TITLE
Fix contributors count badge on amphtml

### ISSUE THREAD

**Issue by estherkim** [ampproject/amp-github-apps#475] opened 2019-09-24 22:43 UTC
The contributors badge count is different than the repo's contributor count
![image](https://user-images.githubusercontent.com/44627152/65555599-0bf0d180-defb-11e9-9f76-facaf5716de1.png)
and
![image](https://user-images.githubusercontent.com/44627152/65555606-101cef00-defb-11e9-8a71-e40342a256c7.png)

cc/ @ampproject/wg-infra

**Comment by rcebulko** [comment] 2019-09-24 22:51
The shields.io endpoint being used includes anon contributors. See [here](https://shields.io/category/activity) and [here](https://stackoverflow.com/questions/36410357/github-v3-api-list-contributors). I assume this was intentional; if it should be the same as the tab, I think it should be removed altogether.

**Comment by estherkim** [comment] 2019-09-25 15:10
Hmm I see. I think it's redundant and vote to remove.

**Comment by estherkim** [comment] 2019-10-08 19:00
cc @sudhanemani if you want to look at this also!

**Comment by rsimha** [comment] 2019-10-08 20:20
Good catch @estherkim!

Badge is being removed in https://github.com/ampproject/amphtml/pull/24964. Root cause of inaccuracy is https://github.com/badges/shields/issues/764.

**Comment by rcebulko** [comment] 2019-12-05 16:13
Closed by https://github.com/ampproject/amphtml/pull/25816

**Comment by rcebulko** [comment] 2019-12-05 16:13
(mistakenly closed, confused this for a similar issue)

**Comment by rcebulko** [comment] 2020-01-07 15:56
Closed by https://github.com/ampproject/amphtml/pull/24964

**Closed by rcebulko** 2020-01-07 15:56 UTC
