### ISSUE TITLE
Build-size's resolve link should force a recheck

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amp-github-apps#269] opened 2019-07-22 18:27 UTC
Eg, https://github.com/ampproject/amphtml/pull/23442/checks?check_run_id=173583540. The "resolve" link (https://amp-bundle-size-bot.appspot.com/) should allow us to force the build-size bot to recheck the GH approvals.

**Comment by danielrozenberg** [comment] 2019-07-22 18:29
That makes sense. I wonder if the PR approval model is the best way, or whether we should move to an explicit approval of the check using an action button (which is a relatively new feature for GitHub Apps, that's why it wasn't considered before)

wdyt?

**Comment by jridgewell** [comment] 2019-07-22 18:30
I like being able to approve a PR with a general PR approval, though. Would this require me to hit a second button?

**Comment by danielrozenberg** [comment] 2019-07-22 18:31
It would (from the PR you'd have to click the `Details` link on the check, and then the `Approve` link). So you prefer the current approach

**Comment by danielrozenberg** [comment] 2019-07-22 18:33
Hmm... the problem with re-running the check to verify the approvals is that it can't tell these two scenarios apart:

1. bundle-size approval is required → PR is approved → some error causes the approval not to be registered
2. bundle-size approval is required → PR is approved → commit is pushed → bundle-size approval is required again

**Comment by rsimha** [comment] 2019-07-22 18:36
One advantage of separating general PR approval from size-increase approval is that a reviewer who happens to be a bundle-size owner a review a PR without inadvertently allowing the size increase to sneak through. I'll defer to @danielrozenberg's judgement on this, since he's more aware of the corner cases.

While on the topic of approvals, I'd like to make a case for #141, which proposes that we switch the size increase approvers from a hard-coded list to the runtime working group. WDYT?

**Comment by jridgewell** [comment] 2019-07-22 18:41
Shouldn't it be checking the order of commits/approval?

**Comment by danielrozenberg** [comment] 2019-07-22 18:47
I'll have to check whether the API supports that, but it does complicate the app's code 1,000× >__>

**Comment by danielrozenberg** [comment] 2019-08-05 19:13
We discussed this offline in the infra team and came to agree that fixing this is not worth the effort, given the rarity of the root cause (GitHub API/webhook failures) - the easiest solution in those cases is to rebase the last commit or close/reopen the PR. I'm going to close this issue as a won't-fix

**Closed by danielrozenberg** 2019-08-05 19:13 UTC
Labels: Category: Bundle Size, P2: Soon, Type: Bug
