### ISSUE TITLE
Extra info in bundle-size bot output

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#787] opened 2020-04-21 18:26 UTC
I've been added to a handful of PRs by the bundle-size bot. In many cases, the failure is because the artifacts hadn't uploaded yet, and I have to re-run the Travis job to fix it (then I sometimes need to unsubscribe from the thread. In other cases, it asks for my approval, but it's not clear to me when I should or shouldn't approve something. Additionally, PRs that affect many bundle sizes don't show which ones passed the threshold, and only show the delta in KB but not % change.

Feature requests:
- Don't automatically add a reviewer when the check fails because of an error
- Include % change for bundle files
- Boldface the lines that correspond to bundle sizes that went past the threshold

/tryassign @danielrozenberg

**Comment by danielrozenberg** [comment] 2021-02-24 20:31
> * Don't automatically add a reviewer when the check fails because of an error

Duplicate of #857

> * Include % change for bundle files

We rarely handle the question of percentages, raw KB increases are what we care about

> * Boldface the lines that correspond to bundle sizes that went past the threshold

Will do in a PR :)

**Closed** 2021-02-24 20:53 UTC
Labels: Category: Bundle Size, P2: Soon, Type: Feature Request
