### ISSUE TITLE
[owners] Provide a mechanism to allow certain files to be exempt from owners checks

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-github-apps#286] opened 2019-07-23 17:47 UTC
For example, package.json gets updated very frequently by the renovate bot. A build cop should be able to approve and merge those PRs without needing a review from the individual owners of the root directory (or that file).

**Comment by rcebulko** [comment] 2019-08-13 21:33
Possible duplicate, or at least relation to, #283

**Comment by rcebulko** [comment] 2019-09-03 16:54
Closing as a duplicate of #279

**Closed by rcebulko** 2019-09-03 16:54 UTC
Labels: Category: Owners, P1: High Priority, Type: Feature Request
