### ISSUE TITLE
Apply a failed status when tests fail

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#135] opened 2019-05-24 22:30 UTC
Today, failing checks result in a neutral status. These should be red X marks. (Unless there's a reason why this can't be done yet?)

![image](https://user-images.githubusercontent.com/26553114/58359521-dc00c700-7e51-11e9-8196-07bb56210330.png)

**Comment by danielrozenberg** [comment] 2019-05-24 22:32
Duplicate of #102 (context in PR #103)

**Closed by danielrozenberg** 2019-05-24 22:32 UTC

**Comment by rsimha** [comment] 2019-05-27 20:38
Gotcha. In that case, let's fix #102 soon.
