### ISSUE TITLE
[owners] Better link to status message

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-github-apps#280] opened 2019-07-23 17:41 UTC
For AMP this might be an OK link
https://github.com/ampproject/amphtml/blob/master/GOVERNANCE.md#owners

But we should probably have a dedicated doc in https://github.com/ampproject/amphtml/tree/master/contributing

**Comment by rcebulko** [comment] 2019-08-13 21:39
I'm not clear on what the "status message" is referring to

**Comment by rcebulko** [comment] 2019-09-03 16:56
@erwinmombay Can you add some context on this? I'm not clear on what needs to be updated

**Comment by rcebulko** [comment] 2019-09-06 19:34
Closing as obsolete/duplicate of #282

**Closed by rcebulko** 2019-09-06 19:34 UTC
Labels: Category: Owners, P3: When Possible, Type: Feature Request
